---
title: "Project 8"
author: "biRd-studio"
date: "2023-12-03"
output: html_document
bibliography: "BIOL3140.bib"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction 
The term trans-Gulf migrants (TGMs) are a group of birds undertaking extensive non-stop flights across the Gulf of Mexico, ultimately landing between Texas and Florida. These birds are integral members of a larger cohort migrating from Central and South American to more temperate regions. Evolutionary trade-offs, as discussed by @Newton2008 and @Smith2005, hinge on whether early arrivals have better chances of finding mates and breeding multiple times or if later arrivals benefit from increased food availability. 

Researchers are particularly interested in TGM arrival dates due to their implications for fitness, especially considering the influence of climate change on these dates. According to @Both2006, rising spring temperatures may lead to a decline in TGM populations if they fail to adjust their breeding site arrival dates accordingly. Additionally studies from @Cook2021 show that cold weather and high population density adversely affect survival rates. As climate change induces irregular temperature and weather patterns, TGMs face fluctuations in survival rates. 

In 2002m the Cornell Laboratory of Ornithology and the National Audubon Society introduced eBird, a program empowering citizen scientists and birders to share their observations, creating a comprehensive bird sighting database. This initiative has emerged as a crucial tool for advancing avian biology studies.

Our project aims to leverage eBird and meteorological data to comprehend the impact of local weather conditions on TGM arrivals in Massachusetts. Through this, we seek to enhance our understanding of how TGMs respond to changing environmental conditions and contribute valuable insights to avian biology research. 

## Methods 
Our initial step involved five distinct trans-Gulf migrant (TGM) bird species, each belonging to different families. The species that we chose are the following: (insert the 5 names when chosen). Human observations of these species in Massachusetts, extracted from the eBird database, constituted our primary data source. In order to extract information from the eBird database, we utilized the occ_data() function from rgbif, which queries GBIF occurrences, therefore allowing us to acquire the occurrence data for the selected species. Additionally, the dataset facilitated the determination of the Julian day for each species, enabling an examination of the influence of temperature and wind along their migration route to Massachusetts. 

Our investigation encompassed three key locations along the migration path: Mobile AL (Gulf initiation point), Charlotte, NC (midpoint), and Boston, MA (final destination). Weather data from each location was retrieved using a NOAA website token. Subsequently, we plotted the eBird data to depict the proportion of the population that arrived and the predicted arrival time for each species. Furthermore, a plot was generated to illustrate the temporal variations in the Julian day over the years, facilitating an assessment of climate impact on arrival dates. 

Wind direction was computed using weather data, and the results were integrated with the species data. Utilizing the frollmean() function, we calculated the mean of weather variables for both 5 and 10 days preceding the arrival day. 

Moreover, we constructed a Linear Mixed-effect Model using the lme package for both the single-day and two-week average weather datasets. An Anova test was conducted to identify the model with the best fit, and model testing was done with the dredge() function. This approach allowed us to comprehensively explore the intricate relationship between weather parameters and the arrival dynamics of the selected TGM bird species along their migratory journey. 

## Results 
## Discussion 

## Author Contributions
Alexandra Hoogendijk

Ava Skogstrom	

Tara Gerjarusak	

Susanne Hahs: Introduction, Methods, Bibliography



## References
